In [5]:
import numpy as np
from tabulate import tabulate
from pprint import pprint


def taskA():
    a = np.zeros((4, 3))
    b = np.ones((4, 3))
    c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

    arrays = [(a, "a"), (b, "b"), (c, "c")]
    for arr, name in arrays:
        print(f"{name}:\n{arr}\nShape: {arr.shape}\n")

taskA()

a:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Shape: (4, 3)

b:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Shape: (4, 3)

c:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Shape: (4, 3)



In [6]:
def taskB():
    def F(x):
        return 2 * x**2 + 5

    x_range = np.arange(1, 101, 1)
    table_data = [(F(x)) for x in x_range]
    data = {"x": x_range, "F(x)": table_data}
    table = tabulate(data, headers="keys", tablefmt="pretty")
    print(table)

taskB()

+-----+-------+
|  x  | F(x)  |
+-----+-------+
|  1  |   7   |
|  2  |  13   |
|  3  |  23   |
|  4  |  37   |
|  5  |  55   |
|  6  |  77   |
|  7  |  103  |
|  8  |  133  |
|  9  |  167  |
| 10  |  205  |
| 11  |  247  |
| 12  |  293  |
| 13  |  343  |
| 14  |  397  |
| 15  |  455  |
| 16  |  517  |
| 17  |  583  |
| 18  |  653  |
| 19  |  727  |
| 20  |  805  |
| 21  |  887  |
| 22  |  973  |
| 23  | 1063  |
| 24  | 1157  |
| 25  | 1255  |
| 26  | 1357  |
| 27  | 1463  |
| 28  | 1573  |
| 29  | 1687  |
| 30  | 1805  |
| 31  | 1927  |
| 32  | 2053  |
| 33  | 2183  |
| 34  | 2317  |
| 35  | 2455  |
| 36  | 2597  |
| 37  | 2743  |
| 38  | 2893  |
| 39  | 3047  |
| 40  | 3205  |
| 41  | 3367  |
| 42  | 3533  |
| 43  | 3703  |
| 44  | 3877  |
| 45  | 4055  |
| 46  | 4237  |
| 47  | 4423  |
| 48  | 4613  |
| 49  | 4807  |
| 50  | 5005  |
| 51  | 5207  |
| 52  | 5413  |
| 53  | 5623  |
| 54  | 5837  |
| 55  | 6055  |
| 56  | 6277  |
| 57  | 6503  |
| 58  | 6733  |
| 59  | 6967  |
| 60  | 

In [7]:
def taskC():
    def F(x):
        return np.exp(-x)

    x_range = np.arange(-10, 11, 1)
    table_data = [(F(x)) for x in x_range]
    data = {"x": x_range, "F(x)": table_data}
    table = tabulate(data, headers="keys", tablefmt="pretty")
    print(table)

taskC()

+-----+------------------------+
|  x  |          F(x)          |
+-----+------------------------+
| -10 |   22026.465794806718   |
| -9  |   8103.083927575384    |
| -8  |   2980.9579870417283   |
| -7  |   1096.6331584284585   |
| -6  |   403.4287934927351    |
| -5  |   148.4131591025766    |
| -4  |   54.598150033144236   |
| -3  |   20.085536923187668   |
| -2  |    7.38905609893065    |
| -1  |   2.718281828459045    |
|  0  |          1.0           |
|  1  |  0.36787944117144233   |
|  2  |   0.1353352832366127   |
|  3  |  0.049787068367863944  |
|  4  |  0.01831563888873418   |
|  5  |  0.006737946999085467  |
|  6  | 0.0024787521766663585  |
|  7  | 0.0009118819655545162  |
|  8  | 0.00033546262790251185 |
|  9  | 0.00012340980408667956 |
| 10  | 4.5399929762484854e-05 |
+-----+------------------------+
